version: '3.1'

services:
  db:
    image: postgres:14.3
    container_name: postgres_rmrk_dao
    restart: always
    ports: 
      - "54323:5432"
    environment:
      POSTGRES_PASSWORD: rmrk_dao
      POSTGRES_USER: rmrk_dao
      POSTGRES_DB: rmrk_dao
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: 
    driver: local